name: Function App CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'BeeSubmitFunction/**'
      - '.github/workflows/function-app.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'BeeSubmitFunction/**'
      - '.github/workflows/function-app.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: southernbeenetwork-api
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './BeeSubmitFunction'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: production
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    - name: 'Deploy to Azure Function App'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_SOUTHERN_BEE_NETWORK_SITE }}
